This code showcase how easy is to develope a model to forecast a time seris, by using PyCaret 3.0.

The aim of this is not to provide the best possibile model, but a better way to manage an ML project.

For more infor read my article on Medium.

In [3]:
import pandas as pd
import numpy as np
from pycaret.time_series import TSForecastingExperiment, get_config, set_current_experiment, models, predict_model
import os

In [4]:
air_pass = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv')
print('Shape of the data= ', air_pass.shape)
print('Column datatypes= \n',air_pass.dtypes)
air_pass

Shape of the data=  (144, 2)
Column datatypes=
 Month         object
Passengers     int64
dtype: object

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [5]:
air_pass['Month'] = pd.to_datetime(air_pass.Month)
air_pass = air_pass.set_index(air_pass.Month)
air_pass.drop(columns=['Month'], inplace = True)
print('Column datatypes= \n',air_pass.dtypes)
air_pass

Column datatypes=
 Passengers    int64
dtype: object

            Passengers
Month
1949-01-01         112
1949-02-01         118
1949-03-01         132
1949-04-01         129
1949-05-01         121
...                ...
1960-08-01         606
1960-09-01         508
1960-10-01         461
1960-11-01         390
1960-12-01         432

[144 rows x 1 columns]

In [6]:
fh = 2 #forecast horizon indicates how many points in the future we want to forecast
experiment = TSForecastingExperiment()
experiment.setup(data=air_pass, fh=fh, target='Passengers', session_id=42)

In [7]:
experiment.check_stats()

,Test,Test Name,Data,Property,Setting,Value
0,Summary,Statistics,Transformed,Length,,144.0
1,Summary,Statistics,Transformed,# Missing Values,,0.0
2,Summary,Statistics,Transformed,Mean,,280.298611
3,Summary,Statistics,Transformed,Median,,265.5
4,Summary,Statistics,Transformed,Standard Deviation,,119.966317
5,Summary,Statistics,Transformed,Variance,,14391.917201
6,Summary,Statistics,Transformed,Kurtosis,,-0.364942
7,Summary,Statistics,Transformed,Skewness,,0.58316
8,Summary,Statistics,Transformed,# Distinct Values,,118.0
9,White Noise,Ljung-Box,Transformed,Test Statictic,"{'alpha': 0.05, 'K': 24}",1606.083817
10,White Noise,Ljung-Box,Transformed,Test Statictic,"{'alpha': 0.05, 'K': 48}",1933.155822
11,White Noise,Ljung-Box,Transformed,p-value,"{'alpha': 0.05, 'K': 24}",0.0
12,White Noise,Ljung-Box,Transformed,p-value,"{'alpha': 0.05, 'K': 48}",0.0
13,White Noise,Ljung-Box,Transformed,White Noise,"{'alpha': 0.05, 'K': 24}",False
14,White Noise,Ljung-Box,Transformed,White Noise,"{'alpha': 0.05, 'K': 48}",False
15,Stationarity,ADF,Transformed,Stationarity,{'alpha': 0.05},False
16,Stationarity,ADF,Transformed,p-value,{'alpha': 0.05},0.99188
17,Stationarity,ADF,Transformed,Test Statistic,{'alpha': 0.05},0.815369
18,Stationarity,ADF,Transformed,Critical Value 1%,{'alpha': 0.05},-3.481682
19,Stationarity,ADF,Transformed,Critical Value 5%,{'alpha': 0.05},-2.884042
20,Stationarity,ADF,Transformed,Critical Value 10%,{'alpha': 0.05},-2.57877
21,Stationarity,KPSS,Transformed,Trend Stationarity,{'alpha': 0.05},True
22,Stationarity,KPSS,Transformed,p-value,{'alpha': 0.05},0.1
23,Stationarity,KPSS,Transformed,Test Statistic,{'alpha': 0.05},0.09615
24,Stationarity,KPSS,Transformed,Critical Value 10%,{'alpha': 0.05},0.119
25,Stationarity,KPSS,Transformed,Critical Value 5%,{'alpha': 0.05},0.146
26,Stationarity,KPSS,Transformed,Critical Value 2.5%,{'alpha': 0.05},0.176
27,Stationarity,KPSS,Transformed,Critical Value 1%,{'alpha': 0.05},0.216
28,Normality,Shapiro,Transformed,Normality,{'alpha': 0.05},False
29,Normality,Shapiro,Transformed,p-value,{'alpha': 0.05},0.000068

In [8]:
metric = 'mape'
n_select = 1
best_model = experiment.compare_models(sort=metric,  n_select = n_select)

Processing:   0%|          | 0/121 [00:00<?, ?it/s]

In [10]:
experiment.predict_model(best_model)

           y_pred
1960-11  408.5898
1960-12  443.6479